after(b, v).
after(d, a).
after(a, i).
after(b, a).
after(w, a).
after(c, a).
after(y, v).
after(c, z).
before(a, b).
before(a, c).
before(f, q).
before(y, b).
equals(f, v).
equals(v, f).
finishes(n, m).
finishes(n, k).
finishes(j, k).
finished_by(m, n).
started_by(i, l).
started_by(a, g).
started_by(i, a).
starts(l, i).
starts(a, i).
meets(q, w).
meets(u, q).
met_by(u, r).
during(g, f).
during(r, q).
contains(f, g).
contains(e, g)
overlaps(w, u).
overlaps(u, o).
overlapp_by(u, w).
overlapp_by(u, o).